# Generated by Django 3.2.10 on 2021-12-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=150, null=True)),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('GovtIssuedId', models.CharField(max_length=150, null=True)),
                ('GovtIssuedIdNo', models.CharField(max_length=150, null=True)),
                ('FullAddress', models.CharField(max_length=350, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=100, null=True)),
                ('FullName', models.CharField(max_length=150, null=True)),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNumber', models.CharField(max_length=50, null=True)),
                ('TestType', models.CharField(max_length=250, null=True)),
                ('TestTimeSlot', models.CharField(max_length=150, null=True)),
                ('ReportStatus', models.CharField(max_length=200, null=True)),
                ('FinalReport', models.CharField(max_length=200, null=True)),
                ('ReportUploadTime', models.DateTimeField(auto_now_add=True)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
                ('AssignedTime', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.phlebotomist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Reporttracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(max_length=150, null=True)),
                ('PostingTime', models.DateTimeField(auto_now_add=True)),
                ('RemarkBy', models.CharField(max_length=150, null=True)),
                ('testRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.testrecord')),
            ],
        ),
    ]
