# Generated by Django 3.2.10 on 2021-12-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='AssignedTime',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.phlebotomist'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='ReportUploadTime',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
