# Generated by Django 3.2.10 on 2021-12-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20211228_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrecord',
            old_name='Employee',
            new_name='phlebotomist',
        ),
    ]
