# Generated by Django 3.2.10 on 2021-12-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_rename_employee_testrecord_phlebotomist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('emailid', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('symptoms', models.CharField(max_length=150, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
                ('msgdate', models.DateField(null=True)),
                ('isread', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
