# Generated by Django 3.1.3 on 2022-01-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20220102_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttracking',
            name='RemarkBy',
        ),
    ]
