# Generated by Django 3.1.3 on 2022-01-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_remove_reporttracking_remarkby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='FinalReport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
